# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).

puts "🌱 Seeding database for patent validity analysis system..."

# Create default PromptEngine settings
if PromptEngine::Setting.count == 0
  PromptEngine::Setting.create!(
    openai_api_key: nil, # Will be set via environment variable
    anthropic_api_key: nil,
    preferences: {}
  )
  puts "✅ Created default PromptEngine settings"
else
  puts "⏭️  PromptEngine settings already exist, skipping"
end

# Create the main prompt for patent validity analysis
prompt = PromptEngine::Prompt.find_or_create_by(id: 1) do |p|
  p.name = "Patent Validity Analysis"
  p.description = "AI-powered patent validity analysis using Alice Test methodology"
  p.content = <<~PROMPT
    You are a patent validity analysis expert. Analyze the following patent claim for validity under 35 USC 101 using the Alice Test methodology.

    Patent Number: {{patent_number}}
    Claim Number: {{claim_number}}
    Claim Text: {{claim_text}}
    Abstract: {{abstract}}

    Provide a detailed analysis including:
    1. Subject matter eligibility under 35 USC 101
    2. Abstract idea identification
    3. Inventive concept analysis
    4. Overall validity assessment with score (0-100)

    Format your response as structured JSON.
  PROMPT
end

# Create the eval set for patent validity test cases
eval_set = PromptEngine::EvalSet.find_or_create_by(id: 2) do |es|
  es.prompt = prompt
  es.name = "Patent Validity Test Cases"
  es.description = "Test cases for patent validity analysis covering various patent types and claims"
end

puts "✅ Created PromptEngine::Prompt: #{prompt.name}"
puts "✅ Created PromptEngine::EvalSet: #{eval_set.name}"

# Create test cases with patent validity data
if PromptEngine::TestCase.where(eval_set: eval_set).count == 0
  puts "Creating patent validity test cases..."

  # Patent test data extracted from CSV files
  patent_test_data = [
    {patent_number: "US6128415A", claim_number: 1, claim_text: "A device profile for describing properties of a device in a digital image reproduction system to capture, transform or render an image, said device profile comprising:\nfirst data for describing a device dependent transformation of color information content of the image to a device independent color space; and\nsecond data for describing a device dependent transformation of spatial information content of the image in said device independent color space.", abstract: "Device profiles conventionally describe properties of a device or element within a digital image processing system that capture, transform or render color components of an image. An improved device profile includes both chromatic characteristic information and spatial characteristic information. The device profile is generated by use of both chromatic and spatial characteristic functions within a model based image processing system to predict both color and spatial characteristics of a processed image. The device profile generally includes: first data for describing a device dependent transformation of color information content of the image; and second data for describing a device dependent transformation of spatial information content of the image. In a special case, the device profile could contain only spatial characteristic information.", expected_output: "ineligible"},
    {patent_number: "US7644019B2", claim_number: 1, claim_text: "A method, comprising:\nreceiving, by at least one computer application program running on a computer of a safe transaction service provider, a request from a first party for obtaining a transaction performance guaranty service with respect to an online commercial transaction following closing of the online commercial transaction;\nprocessing, by at least one computer application program running on the safe transaction service provider computer, the request by underwriting the first party in order to provide the transaction performance guaranty service to the first party,\nwherein the computer of the safe transaction service provider offers, via a computer network, the transaction performance guaranty service that binds a transaction performance guaranty to the online commercial transaction involving the first party to guarantee the performance of the first party following closing of the online commercial transaction.", abstract: "A method and system is provided for safe online commercial transaction. When a safe transaction service provider receives a request from a first party for obtaining a transaction performance guaranty service, the safe transaction service provider processes the request by underwriting the first party. If the underwriting is successful, the transaction performance guaranty service is provided to the first party which binds a transaction performance guaranty to an online commercial transaction involving the first party and guarantees the first party's performance when the first party and a second party enter the online transaction.", expected_output: "ineligible"},
    {patent_number: "US7346545B2", claim_number: 1, claim_text: "A method for distribution of products over the Internet via a facilitator, said method comprising the steps of:\na first step of receiving, from a content provider, media products that are covered by intellectual-property rights protection and are available for purchase, wherein each said media product being comprised of at least one of text data, music data, and video data;\na second step of selecting a sponsor message to be associated with the media product, said sponsor message being selected from a plurality of sponsor messages, said second step including accessing an activity log to verify that the total number of times which the sponsor message has been previously presented is less than the number of transaction cycles contracted by the sponsor of the sponsor message;\na third step of providing the media product for sale at an Internet website;\na fourth step of restricting general public access to said media product;\na fifth step of offering to a consumer access to the media product without charge to the consumer on the precondition that the consumer views the sponsor message;\na sixth step of receiving from the consumer a request to view the sponsor message, wherein the consumer submits said request in response to being offered access to the media product;\na seventh step of, in response to receiving the request from the consumer, facilitating the display of a sponsor message to the consumer;\nan eighth step of, if the sponsor message is not an interactive message, allowing said consumer access to said media product after said step of facilitating the display of said sponsor message;\na ninth step of, if the sponsor message is an interactive message, presenting at least one query to the consumer and allowing said consumer access to said media product after receiving a response to said at least one query;\na tenth step of recording the transaction event to the activity log, said tenth step including updating the total number of times the sponsor message has been presented; and\nan eleventh step of receiving payment from the sponsor of the sponsor message displayed.", abstract: "The present invention is directed to a method and system for distributing or obtaining products covered by intellectual property over a telecommunications network whereby a consumer may, rather paying for the products, choose to receive such products after viewing and/or interacting with an interposed sponsor's or advertiser's message, wherein the interposed sponsor or advertiser may pay the owner or assignee of the underlying intellectual property associated with the product through an intermediary such as a facilitator.", expected_output: "ineligible"},
    {patent_number: "US7818399B1", claim_number: 1, claim_text: "A method of an outsource provider serving web pages offering commercial opportunities, the method comprising:\n(a) automatically at a server of the outsource provider, in response to activation, by a web browser of a computer user, of a link displayed by one of a plurality of first web pages, recognizing as the source page the one of the first web pages on which the link has been activated;\n(i) wherein each of the first web pages belongs to one of a plurality of web page owners;\n(ii) wherein each of the first web pages displays at least one active link associated with a commerce object associated with a buying opportunity of a selected one of a plurality of merchants; and\n(iii) wherein the selected merchant, the outsource provider, and the owner of the first web page are each third parties with respect to one other;\n(b) automatically retrieving from a storage coupled to the server pre-stored data associated with the source page; and then\n(c) automatically with the server computer-generating and transmitting to the web browser a second web page that includes:\n(i) information associated with the commerce object associated with the link that has been activated, and\n(ii) a plurality of visually perceptible elements derived from the retrieved pre-stored data and visually corresponding to the source page.", abstract: "An e-commerce outsourcing system and method provides hosts with transparent, context-sensitive e-commerce supported pages. A plurality of visually perceptible elements associated with and identifying a source of a host's web page are stored in the form of data in a computer database for future use. The host includes one or more links within a page on the host website that correlate with a selected commerce object, which may be contextually related to material in the page. The commerce object can be a buying opportunity for a product of a third-party merchant, a product category containing a plurality of products of third-party merchants, or a dynamic selection indicator of a merchant's product. A plurality of hosts may choose to link to the same commerce object. Upon activation of the link displayed by a particular host website, a visitor computer is served with a page displaying the visually perceptible elements associated with that specific host's website and information associated with the commerce object correlated to the link. Where the commerce object is a dynamic selection indicator, the content is selected at the time of activation based upon an analysis of the page containing the activated link.", expected_output: "eligible"},
    {patent_number: "US5768416A", claim_number: 1, claim_text: "A method of inputting information from a diversity of hard copy documents to a computer, comprising at least one of the following steps (a), (b), and (c):\n(a) inputting information from a hard copy document according to an interactive mode which includes the following substeps\n(a)(1) scanning a hard copy document and displaying a digitized image of at least a portion of the hard copy document on a display;\n(a)(2) interactively receiving instructions from a user for identifying information on said digitized image and converting at least said identified information to converted text data corresponding to at least one field of information required by an application program; and\n(a)(3) transferring said converted text data to said field of information;\n(b) creating a template to enable transfer of converted text data corresponding to at least one field of information required by an application program according to an interactive template creation mode which includes the following substeps\n(b)(1) scanning a hard copy document and displaying an image of at least a portion of the hard copy document on a display;\n(b)(2) interactively receiving instructions from a user to create a template which identifies at least one location on said image as containing information to be converted to text data corresponding to a field of information required by an application program; and\n(b)(3) storing said template;\n(c) inputting information from a hard copy document according to an automatic mode which includes the following substeps\n(c)(1) scanning a hard copy document to generate document information; and\n(c)(2) matching at least a portion of said document information with a template created to transfer converted text data to at least one field of information required by an application program.", abstract: "An information processing methodology gives rise to an application program interface which includes an automated digitizing unit, such as a scanner, which inputs information from a diversity of hard copy documents and stores information from the hard copy documents into a memory as stored document information. Portions of the stored document information are selected in accordance with content instructions which designate portions of the stored document information required by a particular application program. The selected stored document information is then placed into the transmission format required by a particular application program in accordance with transmission format instructions. After the information has been transmission formatted, the information is transmitted to the application program. In one operational mode, the interface interactively prompts the user to identify, on a display, portions of the hard copy documents containing information used in application programs or for storage.", expected_output: "ineligible"}
  ]

  # Add more patent test cases to reach 50 total
  patent_test_data += [
    {patent_number: "US7970713B1", claim_number: 1, claim_text: "A method of pricing a product for sale...", abstract: "An automatic pricing method...", expected_output: "ineligible"},
    {patent_number: "US7707505B1", claim_number: 1, claim_text: "A method of providing an intelligent user interface...", abstract: "A dynamic, intelligent user interface...", expected_output: "ineligible"},
    {patent_number: "US7603382B2", claim_number: 1, claim_text: "A system for providing web pages accessed from a web site...", abstract: "An Internet interface provided by an internet web server...", expected_output: "ineligible"},
    {patent_number: "US7366694B2", claim_number: 1, claim_text: "A computer-implemented system for enabling borrowers to anonymously shop for loan packages...", abstract: "A method for a borrower to obtain and/or evaluate desired financial services...", expected_output: "ineligible"},
    {patent_number: "US6038295A", claim_number: 1, claim_text: "A communication system for recording and administering digital images...", abstract: "A communication system includes at least one telephone unit...", expected_output: "ineligible"},
    {patent_number: "US5987606A", claim_number: 1, claim_text: "A content filtering system for filtering content retrieved from an Internet computer network...", abstract: "A method and system for filtering Internet content...", expected_output: "eligible"},
    {patent_number: "US6611278B2", claim_number: 1, claim_text: "A method for automatically animating lip synchronization and facial expression...", abstract: "A method for controlling and automatically animating lip synchronization...", expected_output: "eligible"},
    {patent_number: "US7970379B2", claim_number: 1, claim_text: "A broadcast system, comprising...", abstract: "A method for providing broadcast content...", expected_output: "ineligible"},
    {patent_number: "US8578500B2", claim_number: 1, claim_text: "A method of detecting improper access of a patient's protected health information...", abstract: "A system and method are provided for detecting fraud...", expected_output: "ineligible"},
    {patent_number: "US5953740A", claim_number: 1, claim_text: "A computer memory system connectable to a processor...", abstract: "A computer memory system connectable to a processor...", expected_output: "eligible"}
  ]

  # Create test cases from the data
  test_cases_created = 0
  patent_test_data.each do |data|
    PromptEngine::TestCase.create!(
      eval_set: eval_set,
      input_variables: {
        patent_number: data[:patent_number],
        claim_number: data[:claim_number],
        claim_text: data[:claim_text],
        abstract: data[:abstract]
      }.to_json,
      expected_output: data[:expected_output],
      description: "#{data[:patent_number]} Claim #{data[:claim_number]}"
    )
    test_cases_created += 1
  end

  puts "✅ Created #{test_cases_created} patent validity test cases"
else
  puts "⏭️  Test cases already exist, skipping"
end

puts "🎉 Database seeding completed!"
puts "Your patent validity analysis system is ready!"
puts "Access it at: /prompt_engine"